### ISSUE TITLE
what is "train.rouge_bigram_F1.oracle.F1mmrTrue.regGain"

### ISSUE THREAD

**Issue by BIGKUANG** [magic282/NeuSum#1]
Hi :
    I'm interested in your paper,  but I  didn't quite understande the file of "train.rouge_bigram_F1.oracle.F1mmrTrue.regGain", can you describe it  more detail in "read.me" or provides the code of generated this file. Thank you very much for your work!

**Comment by magic282** [comment]
Hi @BIGKUANG , the basic idea is described in section 5.1 in the paper. The file contains the ROUGE-2 F1 score gain as indicated by the filename. Take the first line as an example. The first sentences is 1, so we can calculate ROUGE score of all sentences and the current ROUGE score is 0.258064516129 and the extracted sentence set is S={1}. In the next step, we again add each sentence to S, and get ROUGE scores of these candidate extracted set. Then we subtract 0.258064516129 from them to get the second step ROUGE score gain.

You can easily get how it is produced through this example: https://gist.github.com/magic282/e4b2ecc91f185939b2688863ae9e41c1

**Comment by BIGKUANG** [comment]
Thanks for your reply, that is  a more ingenious way of thinking.
