### ISSUE TITLE
How can be the sentences separate using ##SENT##?

### ISSUE THREAD

**Issue by CarolLi** [magic282/NeuSum#12]
I can not figure out how the .src file and .tgt file generated using your work, therefore, I want to write some code to implement the goal.  
And I found that the sentences in .tgt and .src are separate using ##SENT## where the sentence might contain several '.'s in it, here gives one example in train.txt.src.100.

> ##SENT##`` I am the son of the president.  You need to get me out of here ! '' one man shouts at me .##SENT##

I tried to use NLTK to get the same result, but it seems like every sentence can only contain one '.'.  Could you tell me what method I can use to reach this goal?

**Comment by magic282** [comment]
Please follow the instructions in https://github.com/magic282/cnndm_acl18

**Comment by CarolLi** [comment]
> Please follow the instructions in https://github.com/magic282/cnndm_acl18

I've read it several times, but I still can not figure it out, Sorry for that.  As my understanding, the preprocessing files in abisee's work is train.bin, test.bin and val.bin, which are absolutely not the same with the files in yours.  I've run abisee's work before, but as far as I know, the data in her work does not mention anything about the "##SENT##" separator, so I am very confused.

**Comment by magic282** [comment]
1. Write some code to read the text from those abisee's bin file (or modify her code to write to text files).
2. Write the text as the sample format.
3. Run the code to get the oracle and gain files.

**Comment by CarolLi** [comment]
> 1. Write some code to read the text from those abisee's bin file (or modify her code to write to text files).
> 2. Write the text as the sample format.
> 3. Run the code to get the oracle and gain files.

Oh, I see~  Thank you!
