### ISSUE TITLE
Testing of model

### ISSUE THREAD

**Issue by princeamitlali** [magic282/NeuSum#13]
We have build the model but not be able to test the model.please suggest some steps to do so.

**Comment by magic282** [comment]
Please use `summarize.py`.

**Comment by princeamitlali** [comment]
do i have to pass any directory or file address with summarize.py ?
and also it is very useful if you send the output file.

**Comment by CarolLi** [comment]
Same question, how can I do the validation and evaluation with the model?  I ran` python summarize.py`, but it is hard for me to understand what arguments and their values I should put in the command.  What's the meaning of the argument with the brackets, does it mean the non-essential argument?
`usage: summarize.py [-h] -model MODEL -src SRC [-tgt TGT] [-output OUTPUT]
                    [-beam_size BEAM_SIZE] [-batch_size BATCH_SIZE]
                    [-max_sent_length MAX_SENT_LENGTH] [-replace_unk]
                    [-verbose] [-n_best N_BEST] [-max_doc_len MAX_DOC_LEN]
                    [-max_decode_step MAX_DECODE_STEP] [-force_max_len]
                    [-gpu GPU]`

**Comment by magic282** [comment]
For example:
```bash
python summarize.py \
        -model ${SAVEPATH}/model_devRouge_0.1965_e8.pt \
        -src ${DATAHOME}/test/test.src.txt \
        -output ${SAVEPATH}/test.src.txt.neusum_out \
        -max_decode_step 3 -force_max_len \
        -beam_size 1 -batch_size 64 \
        -gpu 0
```
