### ISSUE TITLE
Model.pt file

### ISSUE THREAD

**Issue by princeamitlali** [magic282/NeuSum#14]
How to generate model.pt file? help is required

**Comment by CarolLi** [comment]
I think the argument "-dump_epoch_checkpoint" is needed in the run.sh.

**Comment by CarolLi** [comment]
Maybe your training data is not enough, I met this situation either, but I generate the .pt file by adjusting the values of -start_eval_batch and -eval_per_batch.

**Comment by princeamitlali** [comment]
May i get a pre-trained model ? If any one can help, i will be very greatful.
