### ISSUE TITLE
Why vocab file generated only by tgt.txt?

### ISSUE THREAD

**Issue by CarolLi** [magic282/NeuSum#19]
In CollectVocab.py, why the tgt.txt file rather than both of the src.txt and tgt.txt was used to generate the vocab file?
```
if __name__ == "__main__":
    # files = [r"D:\users\v-qizhou\data\SongCi\v1\train\src.txt",
    #          r"D:\users\v-qizhou\data\SongCi\v1\train\tgt.txt"]
    # vocab_file = r"D:\users\v-qizhou\data\SongCi\v2\train\vocab.txt"  # TODO pay attention here
    # Collect(files, vocab_file, False, ["<blank>", "<unk>", "<s>", "</s>", "##SP##"])

    # files = [r"D:\users\v-qizhou\data\SongCi\v1\train\src.txt",
    #          r"D:\users\v-qizhou\data\SongCi\v1\train\tgt.txt"]
    # vocab_file = r"D:\users\v-qizhou\data\SongCi\v5\train\vocab.txt"  # TODO pay attention here
    # Collect(files, vocab_file, False, ["<blank>", "<unk>", "<s>", "</s>", "##SP##", "##KEYWORDS##", "##KEYSP##"])

    files = [r"D:\users\v-qizhou\data\SongCi\v7\train\tgt.txt"]
    vocab_file = r"D:\users\v-qizhou\data\SongCi\v7\train\vocab.txt"  # TODO pay attention here
    Collect(files, vocab_file, False, ["<blank>", "<unk>", "<s>", "</s>", "##SP##", "##NOTHING##", "##NONE##"])
```

**Comment by magic282** [comment]
Sorry for the confusing file. It is a general tool script to collect vocabulary. The usage in the file is not for this project. And for your question, you should only collect the vocab from the src.txt since we do not use the target in the model.

**Comment by CarolLi** [comment]
> Sorry for the confusing file. It is a general tool script to collect vocabulary. The usage in the file is not for this project. And for your question, you should only collect the vocab from the src.txt since we do not use the target in the model.

Thank you for your reply~
