### ISSUE TITLE
code for preprocessing the data

### ISSUE THREAD

**Issue by ShuyangCao** [magic282/NeuSum#2]
Hi,

In the paper, you use the same method as https://github.com/abisee/cnn-dailymail to preprocess the data, but the data format used in your code is different. Do you have code for preprocessing the data into your format or can you release your data?

Thanks

**Comment by magic282** [comment]
@Xwai Thank you for reaching out. I am working on a paper deadline so I am considering release the preprocessing code next month.

**Comment by magic282** [comment]
@Xwai The code can be found at https://github.com/magic282/cnndm_acl18 now.

**Comment by ShuyangCao** [comment]
@magic282 Thank you!
