### ISSUE TITLE
Question about input size

### ISSUE THREAD

**Issue by jinziling** [magic282/NeuSum#23]
When i changed the batch_size to 32,I run the train.py file.some errors are as follow,how can i solve these errors?Thank you very much.

  (sent_encoder): Encoder(
    (word_lut): Embedding(197792, 50, padding_idx=0)
    (rnn): GRU(50, 128, dropout=0.3, bidirectional=True)
    (dropout): Dropout(p=0.3)
  )
  (doc_encoder): DocumentEncoder(
    (rnn): GRU(256, 128, dropout=0.2, bidirectional=True)
    (dropout): Dropout(p=0.2)
  )
  (pointer): Pointer(
    (rnn): StackedGRU(
      (dropout): Dropout(p=0.0)
      (layers): ModuleList(
        (0): GRUCell(256, 256)
      )
    )
    (scorer): ScoreAttention(256 * (256->256 + 256->256))
  )
  (decIniter): DecInit(
    (initer): Linear(in_features=128, out_features=256)
  )
)
2019-08-25 20:55:17,747 [WARNING:__main__]: Set model to train mode
2019-08-25 20:55:17,747 [INFO:__main__]: 
2019-08-25 20:55:17,748 [INFO:__main__]: Shuffling...
E:/paper/NeuSum-master/neusum_pt/train.py:68: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  pred_scores = F.log_softmax(pred_scores + 1e-8)
Traceback (most recent call last):
  File "E:/paper/NeuSum-master/neusum_pt/train.py", line 374, in <module>
<class 'torch.Size'> torch.Size([4, 3, 1])
    main()
torch.Size([4, 3, 1])
4 3 1
  File "E:/paper/NeuSum-master/neusum_pt/train.py", line 370, in main
    trainModel(model, summarizer, trainData, validData, dataset, optim)
  File "E:/paper/NeuSum-master/neusum_pt/train.py", line 290, in trainModel
    train_reg_loss = trainEpoch(epoch)
  File "E:/paper/NeuSum-master/neusum_pt/train.py", line 243, in trainEpoch
    reg_loss = regression_loss(doc_sent_scores, gold_sent_rouge_scores, doc_sent_mask, regression_crit)
  File "E:/paper/NeuSum-master/neusum_pt/train.py", line 72, in regression_loss
    gold_scores = gold_scores.view(*pred_scores.size())
RuntimeError: invalid argument 2: size '[4 x 3 x 1]' is invalid for input with 276 elements at D:\pytorch\pytorch\torch\lib\TH\THStorage.c:41

Process finished with exit code 1

**Comment by magic282** [comment]
I just checked the `train.py`. It has only 372 lines and your output shows that line 374 contains an error. I am afraid that you have changed my code. I suggest starting from the `run.sh` file as an example.

**Comment by jinziling** [comment]
Thank you for your reply. I did not modify your code, just added a few print functions to see the output. when i use run.sh as an example, the memory is not enough, so i changed the batch_size to 32. Now this input size has been wrong, I really don't know how to solve it.Can you give me a little thought?
