### ISSUE TITLE
Availability of model output

### ISSUE THREAD

**Issue by jiacheng-xu** [magic282/NeuSum#4]
Hi Qingyu,
   Nice work!  Do you have the output of the model on CNN/DM?

**Comment by magic282** [comment]
@jiacheng-xu Sorry for the late reply. I just found them on our server. How can I send them to you?

**Comment by jiacheng-xu** [comment]
Thanks for the reply. You could send it to jcxu at utexas.edu

**Comment by princeamitlali** [comment]
May i get the output? I am working on your paper and for the same i want to compare the outputs if possible plz send it to   princeamitlali.ml@gmail.com

**Comment by princeamitlali** [comment]
May i get the pre trained model.it will be very helpful if you are able please send it to princeamitlali.ml@gmail.com
