### ISSUE TITLE
TextRank ROUGE Score Reproduction

### ISSUE THREAD

**Issue by SophiaHan6** [magic282/NeuSum#5]
Hi Qingyu, 

TextRank cannot summarise articles with less than three sentences and the CNN/DailyMail dataset has a lot of them. May I ask, to get the ROUGE score on TextRank, how you handled that? 

Thank you.

Regards,
Shirley

**Comment by magic282** [comment]
Select all sentences if the doc is shorter than 3 sents.

**Comment by SophiaHan6** [comment]
Hi Qingyu, 

I've been trying to reproduce your result on TextRank but have not been successful so far. 

Gensim gets 20% of the text by default and it could also generate summaries with a word count. 

May I ask if you generated a certain percentage, or a certain number of words, or a certain number of sentences for the TextRank summary as you did for NeuSum? 

Also, did you handle CNN and DailyMail separately or you handled them in the same way(cuz CNN and DailyMail has different length of gold summary(as stated in [this paper](http://www.aclweb.org/anthology/N18-1158))? 

Thanks!
Shirley
