### ISSUE TITLE
TextRank ROUGE Score Reproduction

### ISSUE THREAD

**Issue by SophiaHan6** [magic282/NeuSum#7]
Hi Qingyu, 

I am trying to reproduce your result on TextRank but my result is around 38 for ROUGE-1, which is two points lower than yours. 

I used the pyrouge package for calculating the ROUGE score. 

May I ask what ROUGE command you used for calculation of the ROUGE score? 

Thank you!
Shirley

**Comment by SophiaHan6** [comment]
(Btw I am also using the entity non-anonymized version of CNN/DailyMail)

**Comment by magic282** [comment]
I think the information you need is in the paper.

**Comment by SophiaHan6** [comment]
Hi Qingyu

I had found in the paper "-m -n 2" and I was also using that command but my result was different. 

Gensim gets 20% of the text by default and it could also generate summaries with a word count.

May I ask if you generated a certain percentage, or a certain number of words, or a certain number of sentences for the TextRank summary as you did for NeuSum?

Also, did you handle CNN and DailyMail separately or you handled them in the same way(cuz CNN and DailyMail has different length of gold summary(as stated in [this paper](http://www.aclweb.org/anthology/N18-1158))?

Thanks in advance for your help!@magic282 
Shirley

**Comment by magic282** [comment]
Select 3 sentences.

**Comment by SophiaHan6** [comment]
Hi Qingyu,

My result is almost the same as yours when I ran ROUGE on three sentences truncated to less number of words. However, if without truncation, my result is a lot lower than yours. 

I understand that your ROUGE command is "-m -n 2" which does not involve truncation. 

However, may I ask if you truncated the summary while performing ROUGE or if you did any data pre-processing or data post-processing? 

Thank you very much!
Shirley

**Comment by magic282** [comment]
I did not truncate the summary.
