### ISSUE TITLE
Require missing data files

### ISSUE THREAD

**Issue by SHALD45** [magic282/NeuSum#9]
Hello,
Your work is really great. Thank you so much for sharing this. One thing I noticed that some files are missing in your run.sh file, i.e.vocab.txt.100k, val.txt.src.shuffle.4k, val.txt.tgt.shuffle.4k. 
Could you please provide these files.
Thanks!

**Comment by CarolLi** [comment]
I also have this problem.  I wondered if the vocab.txt.100k file is similar with the vocab file 
 in https://github.com/abisee/cnn-dailymail.  I tried to use the vocab file as the vocab.txt.100k file, but there existed an error, 
`IndexError: index 11896296 is out of range for dimension 0 (of size 7806)`
It seems like that the vocab file is not suitable in this project, can anyone tell me how to get the vocab.txt.100k file?

**Comment by magic282** [comment]
Hi @SHALD45 @CarolLi , Please build the vocabulary file from the training data using `CollectVocab.py`.
And about the validation set:
The validation set is indeed a 4k random sample. But it does not matter a lot and you can sample your own validation set or use the entire validation set.

**Comment by CarolLi** [comment]
> Hi @SHALD45 @CarolLi , Please build the vocabulary file from the training data using `CollectVocab.py`.
> And about the validation set:
> The validation set is indeed a 4k random sample. But it does not matter a lot and you can sample your own validation set or use the entire validation set.

Got it!  Thank you~

**Comment by CarolLi** [comment]
> Hi @SHALD45 @CarolLi , Please build the vocabulary file from the training data using `CollectVocab.py`.
> And about the validation set:
> The validation set is indeed a 4k random sample. But it does not matter a lot and you can sample your own validation set or use the entire validation set.

I want to confirm a thing.  Which one construct the .tgt file, the highlights from the CNN/DailyMail news or the extracted sentences using the rule-based system?  Thank you again.

**Comment by magic282** [comment]
Of course, `tgt` means the ground truth.

**Comment by NileshPranami** [comment]
@magic282 
Hii Please tell me how can I generate 
al.txt.src.shuffle.4k, 
val.txt.tgt.shuffle.4k.
